### ISSUE TITLE
"fs" is not founded in akord module

### ISSUE THREAD

**Issue by cancan007** [Akord-com/akord-js#169]
I'm trying to use this module in Next.js project to use arweave service. And when I start development next.js project, I got following error.

```
error - ./node_modules/@akord/akord-js/lib/core/file.js:177:76
Module not found: Can't resolve 'fs'
```

I really appreciate any advices.

**Comment by wkolod** [comment]
> I'm trying to use this module in Next.js project to use arweave service. And when I start development next.js project, I got following error.
> 
> ```
> error - ./node_modules/@akord/akord-js/lib/core/file.js:177:76
> Module not found: Can't resolve 'fs'
> ```
> 
> I really appreciate any advices.

Hi @cancan007, thank you for opening the issue!

Here's an example of using akord-js with Next.js: https://github.com/Akord-com/recipes/tree/main/nextjs-starter
To fix `Module not found: Can't resolve "fs"`, you can update your Next.js config file by setting the "fs" fallback to "false" as shown here: 
https://github.com/Akord-com/recipes/blob/8c95a84bf609eecf244dea2607f836ba4eed3011/nextjs-starter/next.config.js#L7

I'm sorry for the inconvenience, the package is for both nodeJS and the browser and this sometimes causes problems, we will try to improve this part so that it works without additional configuration in the future.
Let me know if this helps for now :)

**Comment by cancan007** [comment]
hi, wkolod
Thank you for reply, and it solved!
I really appreciate ur help and u are implementing this module.
